//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::categories::Entity as Categories;
pub use super::comments::Entity as Comments;
pub use super::posts::Entity as Posts;
pub use super::users::Entity as Users;
